[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
"""
body = """
{% if version %}## [{{ version }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/releases/tag/{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}{% else %}## Unreleased{% endif %}
{% for group, commits in commits | group_by(attribute="group") -%}
### {{ group }}
{% for commit in commits -%}
- {{ commit.message | split(pat="\n") | first | trim | upper_first }}{% if commit.remote.username %} by @{{ commit.remote.username }}{% endif %}{% if commit.remote.pr_number %} in [#{{ commit.remote.pr_number }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/pull/{{ commit.remote.pr_number }}){% endif %}
{% endfor %}
{% if not loop.last %}\n{% endif -%}
{% endfor -%}
{% set new_contributors = github.contributors | filter(attribute="is_first_time", value=true) -%}
{% if new_contributors | length > 0 %}

### New Contributors
{% for contributor in new_contributors -%}
- @{{ contributor.username }} made their first contribution{% if contributor.pr_number %} in [#{{ contributor.pr_number }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/pull/{{ contributor.pr_number }}){% endif %}
{% endfor -%}
{% endif -%}
{% if previous.version %}

Full Changelog: [{{ previous.version }}...{{ version }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ previous.version }}...{{ version }})
{% endif %}
"""
trim = true
footer = "<!-- generated by git-cliff -->"

[remote.github]
owner = "JSONbored"
repo = "signoz-aio"

[git]
conventional_commits = true
filter_unconventional = false
require_conventional = false
split_commits = false
protect_breaking_commits = true
tag_pattern = '^v?[0-9].*-aio\\.[0-9]+$'
sort_commits = "oldest"
filter_commits = true
fail_on_unmatched_commit = true
commit_preprocessors = [
  { pattern = " \\(#\\d+\\)$", replace = "" },
  { pattern = " +", replace = " " },
]
link_parsers = [
  { pattern = "#(\\d+)", href = "https://github.com/JSONbored/signoz-aio/issues/$1" },
]
commit_parsers = [
  { message = "^Merge pull request", skip = true },
  { message = "^chore\\(release\\):", skip = true },
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactors" },
  { message = "^docs?", group = "Documentation" },
  { message = "^ci", group = "CI" },
  { message = "^test", group = "Tests" },
  { message = "^build", group = "Build" },
  { message = "^chore\\(deps", group = "Dependency Updates" },
  { message = "^chore", group = "Maintenance" },
  { message = "^revert", group = "Reverts" },
  { message = ".*", group = "Other Changes" },
]
