#!/usr/bin/env bash
# shellcheck shell=bash

AIO_TRUE_VALUES="1 true TRUE yes YES on ON"
AIO_FALSE_VALUES="0 false FALSE no NO off OFF"
AIO_DEFAULT_CLICKHOUSE_DSN="tcp://127.0.0.1:9000"
AIO_DEFAULT_CLICKHOUSE_HEALTHCHECK_URL="http://127.0.0.1:8123/ping"

AIO_BLANK_AS_UNSET_VARS=(
	ALLOW_ANONYMOUS_LOGIN
	LOW_CARDINAL_EXCEPTION_GROUPING
	OTEL_RESOURCE_ATTRIBUTES
	SIGNOZ_AIO_WAIT_TIMEOUT_SECONDS
	SIGNOZ_ALERTMANAGER_PROVIDER
	SIGNOZ_ALERTMANAGER_SIGNOZ_EXTERNAL__URL
	SIGNOZ_ALERTMANAGER_SIGNOZ_ALERTS_GC__INTERVAL
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__IDENTITY
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__PASSWORD
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__PASSWORD_FILE
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__SECRET
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__USERNAME
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__FROM
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__HELLO
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__REQUIRE__TLS
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__SMARTHOST
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__TLS__CA__FILE
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__TLS__CERT__FILE
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__TLS__CONFIG_INSECURE__SKIP__VERIFY
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__TLS__KEY__FILE
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__TLS__MAX__VERSION
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__TLS__MIN__VERSION
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__TLS__SERVER__NAME
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_RESOLVE__TIMEOUT
	SIGNOZ_ALERTMANAGER_SIGNOZ_NFLOG_MAINTENANCE__INTERVAL
	SIGNOZ_ALERTMANAGER_SIGNOZ_NFLOG_RETENTION
	SIGNOZ_ALERTMANAGER_SIGNOZ_POLL__INTERVAL
	SIGNOZ_ALERTMANAGER_SIGNOZ_ROUTE_GROUP__BY
	SIGNOZ_ALERTMANAGER_SIGNOZ_ROUTE_GROUP__INTERVAL
	SIGNOZ_ALERTMANAGER_SIGNOZ_ROUTE_GROUP__WAIT
	SIGNOZ_ALERTMANAGER_SIGNOZ_ROUTE_REPEAT__INTERVAL
	SIGNOZ_ALERTMANAGER_SIGNOZ_SILENCES_MAINTENANCE__INTERVAL
	SIGNOZ_ALERTMANAGER_SIGNOZ_SILENCES_MAX
	SIGNOZ_ALERTMANAGER_SIGNOZ_SILENCES_MAX__SIZE__BYTES
	SIGNOZ_ALERTMANAGER_SIGNOZ_SILENCES_RETENTION
	SIGNOZ_ANALYTICS_ENABLED
	SIGNOZ_ANALYTICS_SEGMENT_KEY
	SIGNOZ_APISERVER_LOGGING_EXCLUDED__ROUTES
	SIGNOZ_APISERVER_TIMEOUT_DEFAULT
	SIGNOZ_APISERVER_TIMEOUT_EXCLUDED__ROUTES
	SIGNOZ_APISERVER_TIMEOUT_MAX
	SIGNOZ_AUDITOR_BATCH__SIZE
	SIGNOZ_AUDITOR_BUFFER__SIZE
	SIGNOZ_AUDITOR_FLUSH__INTERVAL
	SIGNOZ_AUDITOR_OTLPHTTP_ENDPOINT
	SIGNOZ_AUDITOR_OTLPHTTP_INSECURE
	SIGNOZ_AUDITOR_OTLPHTTP_RETRY_ENABLED
	SIGNOZ_AUDITOR_OTLPHTTP_RETRY_INITIAL__INTERVAL
	SIGNOZ_AUDITOR_OTLPHTTP_RETRY_MAX__ELAPSED__TIME
	SIGNOZ_AUDITOR_OTLPHTTP_RETRY_MAX__INTERVAL
	SIGNOZ_AUDITOR_OTLPHTTP_TIMEOUT
	SIGNOZ_AUDITOR_PROVIDER
	SIGNOZ_CACHE_MEMORY_MAX__COST
	SIGNOZ_CACHE_MEMORY_NUM__COUNTERS
	SIGNOZ_CACHE_PROVIDER
	SIGNOZ_CACHE_REDIS_DB
	SIGNOZ_CACHE_REDIS_HOST
	SIGNOZ_CACHE_REDIS_PASSWORD
	SIGNOZ_CACHE_REDIS_PORT
	SIGNOZ_CLICKHOUSE_HEALTHCHECK_URL
	SIGNOZ_CLOUDINTEGRATION_AGENT_VERSION
	SIGNOZ_CLICKHOUSE_LOGS_DSN
	SIGNOZ_CLICKHOUSE_METADATA_DSN
	SIGNOZ_CLICKHOUSE_METER_DSN
	SIGNOZ_CLICKHOUSE_METRICS_DSN
	SIGNOZ_CLICKHOUSE_TRACES_DSN
	SIGNOZ_EMAILING_ENABLED
	SIGNOZ_EMAILING_SMTP_HELLO
	SIGNOZ_EMAILING_SMTP_ADDRESS
	SIGNOZ_EMAILING_SMTP_AUTH_IDENTITY
	SIGNOZ_EMAILING_SMTP_AUTH_PASSWORD
	SIGNOZ_EMAILING_SMTP_AUTH_SECRET
	SIGNOZ_EMAILING_SMTP_AUTH_USERNAME
	SIGNOZ_EMAILING_SMTP_FROM
	SIGNOZ_EMAILING_SMTP_TLS_CA__FILE__PATH
	SIGNOZ_EMAILING_SMTP_TLS_CERT__FILE__PATH
	SIGNOZ_EMAILING_SMTP_TLS_ENABLED
	SIGNOZ_EMAILING_SMTP_TLS_INSECURE__SKIP__VERIFY
	SIGNOZ_EMAILING_SMTP_TLS_KEY__FILE__PATH
	SIGNOZ_EMAILING_TEMPLATES_FORMAT_FOOTER_ENABLED
	SIGNOZ_EMAILING_TEMPLATES_FORMAT_HEADER_ENABLED
	SIGNOZ_EMAILING_TEMPLATES_FORMAT_HEADER_LOGO__URL
	SIGNOZ_EMAILING_TEMPLATES_FORMAT_HELP_EMAIL
	SIGNOZ_EMAILING_TEMPLATES_FORMAT_HELP_ENABLED
	SIGNOZ_ENABLE_HOST_AGENT
	SIGNOZ_FLAGGER_CONFIG_BOOLEAN_KAFKA__SPAN__EVAL
	SIGNOZ_FLAGGER_CONFIG_BOOLEAN_USE__SPAN__METRICS
	SIGNOZ_GLOBAL_EXTERNAL__URL
	SIGNOZ_GLOBAL_INGESTION__URL
	SIGNOZ_GATEWAY_URL
	SIGNOZ_HOST_AGENT_PROMETHEUS_METRICS_PATH
	SIGNOZ_HOST_AGENT_PROMETHEUS_SCRAPE_INTERVAL
	SIGNOZ_HOST_AGENT_PROMETHEUS_TARGETS
	SIGNOZ_IDENTN_APIKEY_ENABLED
	SIGNOZ_IDENTN_APIKEY_HEADERS
	SIGNOZ_IDENTN_IMPERSONATION_ENABLED
	SIGNOZ_IDENTN_TOKENIZER_ENABLED
	SIGNOZ_IDENTN_TOKENIZER_HEADERS
	SIGNOZ_INSTRUMENTATION_LOGS_LEVEL
	SIGNOZ_INSTRUMENTATION_METRICS_ENABLED
	SIGNOZ_INSTRUMENTATION_METRICS_READERS_PULL_EXPORTER_PROMETHEUS_HOST
	SIGNOZ_INSTRUMENTATION_METRICS_READERS_PULL_EXPORTER_PROMETHEUS_PORT
	SIGNOZ_INSTRUMENTATION_TRACES_ENABLED
	SIGNOZ_INSTRUMENTATION_TRACES_PROCESSORS_BATCH_EXPORTER_OTLP_ENDPOINT
	SIGNOZ_METRICSEXPLORER_TELEMETRYSTORE_THREADS
	SIGNOZ_OTEL_COLLECTOR_BATCH_SEND_MAX_SIZE
	SIGNOZ_OTEL_COLLECTOR_BATCH_SEND_SIZE
	SIGNOZ_OTEL_COLLECTOR_BATCH_TIMEOUT
	SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_CLUSTER
	SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN
	SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_REPLICATION
	SIGNOZ_OTEL_COLLECTOR_METER_BATCH_SEND_MAX_SIZE
	SIGNOZ_OTEL_COLLECTOR_METER_BATCH_SEND_SIZE
	SIGNOZ_OTEL_COLLECTOR_METER_BATCH_TIMEOUT
	SIGNOZ_OTEL_COLLECTOR_PPROF_ENDPOINT
	SIGNOZ_OTEL_COLLECTOR_SELF_SCRAPE_INTERVAL
	SIGNOZ_OTEL_COLLECTOR_TIMEOUT
	SIGNOZ_PPROF_ADDRESS
	SIGNOZ_PPROF_ENABLED
	SIGNOZ_PROMETHEUS_TIMEOUT
	SIGNOZ_PROMETHEUS_ACTIVE__QUERY__TRACKER_ENABLED
	SIGNOZ_PROMETHEUS_ACTIVE__QUERY__TRACKER_MAX__CONCURRENT
	SIGNOZ_PROMETHEUS_ACTIVE__QUERY__TRACKER_PATH
	SIGNOZ_QUERIER_CACHE__TTL
	SIGNOZ_QUERIER_FLUX__INTERVAL
	SIGNOZ_QUERIER_MAX__CONCURRENT__QUERIES
	SIGNOZ_RULER_EVAL__DELAY
	SIGNOZ_SERVICEACCOUNT_ANALYTICS_ENABLED
	SIGNOZ_SERVICEACCOUNT_EMAIL_DOMAIN
	SIGNOZ_SQLSTORE_MAX__CONN__LIFETIME
	SIGNOZ_SQLSTORE_MAX__OPEN__CONNS
	SIGNOZ_SQLSTORE_POSTGRES_DSN
	SIGNOZ_SQLSTORE_PROVIDER
	SIGNOZ_SQLSTORE_SQLITE_BUSY__TIMEOUT
	SIGNOZ_SQLSTORE_SQLITE_MODE
	SIGNOZ_SQLSTORE_SQLITE_PATH
	SIGNOZ_SQLSTORE_SQLITE_TRANSACTION__MODE
	SIGNOZ_STATSREPORTER_ENABLED
	SIGNOZ_STATSREPORTER_COLLECT_IDENTITIES
	SIGNOZ_STATSREPORTER_INTERVAL
	SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_CLUSTER
	SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN
	SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_SETTINGS_IGNORE__DATA__SKIPPING__INDICES
	SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_SETTINGS_MAX__BYTES__TO__READ
	SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_SETTINGS_MAX__EXECUTION__TIME
	SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_SETTINGS_MAX__EXECUTION__TIME__LEAF
	SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_SETTINGS_MAX__RESULT__ROWS
	SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_SETTINGS_SECONDARY__INDICES__ENABLE__BULK__FILTERING
	SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_SETTINGS_TIMEOUT__BEFORE__CHECKING__EXECUTION__SPEED
	SIGNOZ_TELEMETRYSTORE_DIAL__TIMEOUT
	SIGNOZ_TELEMETRYSTORE_MAX__IDLE__CONNS
	SIGNOZ_TELEMETRYSTORE_MAX__OPEN__CONNS
	SIGNOZ_TELEMETRYSTORE_PROVIDER
	SIGNOZ_TOKENIZER_JWT_SECRET
	SIGNOZ_TOKENIZER_LIFETIME_IDLE
	SIGNOZ_TOKENIZER_LIFETIME_MAX
	SIGNOZ_TOKENIZER_OPAQUE_GC_INTERVAL
	SIGNOZ_TOKENIZER_OPAQUE_TOKEN_MAX__PER__USER
	SIGNOZ_TOKENIZER_ROTATION_DURATION
	SIGNOZ_TOKENIZER_ROTATION_INTERVAL
	SIGNOZ_USE_EXTERNAL_CLICKHOUSE
	SIGNOZ_VERSION_BANNER_ENABLED
	SIGNOZ_USER_PASSWORD_INVITE_MAX__TOKEN__LIFETIME
	SIGNOZ_USER_PASSWORD_RESET_ALLOW__SELF
	SIGNOZ_USER_PASSWORD_RESET_MAX__TOKEN__LIFETIME
	SIGNOZ_USER_ROOT_EMAIL
	SIGNOZ_USER_ROOT_ENABLED
	SIGNOZ_USER_ROOT_ORG_ID
	SIGNOZ_USER_ROOT_ORG_NAME
	SIGNOZ_USER_ROOT_PASSWORD
	ZOO_ADMIN_SERVER_PORT_NUMBER
	ZOO_AUTOPURGE_INTERVAL
	ZOO_ENABLE_ADMIN_SERVER
	ZOO_ENABLE_PROMETHEUS_METRICS
	ZOO_PROMETHEUS_METRICS_PORT_NUMBER
	ZOO_SERVER_ID
)

AIO_UPSTREAM_AS_UNSET_VARS=(
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__TLS__MAX__VERSION
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__TLS__MIN__VERSION
	SIGNOZ_FLAGGER_CONFIG_BOOLEAN_KAFKA__SPAN__EVAL
	SIGNOZ_FLAGGER_CONFIG_BOOLEAN_USE__SPAN__METRICS
)

AIO_BOOLEAN_VARS=(
	LOW_CARDINAL_EXCEPTION_GROUPING
	SIGNOZ_ANALYTICS_ENABLED
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__REQUIRE__TLS
	SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__TLS__CONFIG_INSECURE__SKIP__VERIFY
	SIGNOZ_AUDITOR_OTLPHTTP_INSECURE
	SIGNOZ_AUDITOR_OTLPHTTP_RETRY_ENABLED
	SIGNOZ_EMAILING_ENABLED
	SIGNOZ_EMAILING_SMTP_TLS_ENABLED
	SIGNOZ_EMAILING_SMTP_TLS_INSECURE__SKIP__VERIFY
	SIGNOZ_EMAILING_TEMPLATES_FORMAT_FOOTER_ENABLED
	SIGNOZ_EMAILING_TEMPLATES_FORMAT_HEADER_ENABLED
	SIGNOZ_EMAILING_TEMPLATES_FORMAT_HELP_ENABLED
	SIGNOZ_ENABLE_HOST_AGENT
	SIGNOZ_FLAGGER_CONFIG_BOOLEAN_KAFKA__SPAN__EVAL
	SIGNOZ_FLAGGER_CONFIG_BOOLEAN_USE__SPAN__METRICS
	SIGNOZ_IDENTN_APIKEY_ENABLED
	SIGNOZ_IDENTN_IMPERSONATION_ENABLED
	SIGNOZ_IDENTN_TOKENIZER_ENABLED
	SIGNOZ_INSTRUMENTATION_METRICS_ENABLED
	SIGNOZ_INSTRUMENTATION_TRACES_ENABLED
	SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_REPLICATION
	SIGNOZ_PPROF_ENABLED
	SIGNOZ_PROMETHEUS_ACTIVE__QUERY__TRACKER_ENABLED
	SIGNOZ_SERVICEACCOUNT_ANALYTICS_ENABLED
	SIGNOZ_STATSREPORTER_ENABLED
	SIGNOZ_STATSREPORTER_COLLECT_IDENTITIES
	SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_SETTINGS_SECONDARY__INDICES__ENABLE__BULK__FILTERING
	SIGNOZ_USE_EXTERNAL_CLICKHOUSE
	SIGNOZ_USER_PASSWORD_RESET_ALLOW__SELF
	SIGNOZ_USER_ROOT_ENABLED
	SIGNOZ_VERSION_BANNER_ENABLED
	ZOO_ENABLE_ADMIN_SERVER
	ZOO_ENABLE_PROMETHEUS_METRICS
)

AIO_INTEGER_VARS=(
	SIGNOZ_AIO_WAIT_TIMEOUT_SECONDS
	SIGNOZ_ALERTMANAGER_SIGNOZ_SILENCES_MAX
	SIGNOZ_ALERTMANAGER_SIGNOZ_SILENCES_MAX__SIZE__BYTES
	SIGNOZ_AUDITOR_BATCH__SIZE
	SIGNOZ_AUDITOR_BUFFER__SIZE
	SIGNOZ_CACHE_MEMORY_MAX__COST
	SIGNOZ_CACHE_MEMORY_NUM__COUNTERS
	SIGNOZ_CACHE_REDIS_DB
	SIGNOZ_CACHE_REDIS_PORT
	SIGNOZ_INSTRUMENTATION_METRICS_READERS_PULL_EXPORTER_PROMETHEUS_PORT
	SIGNOZ_METRICSEXPLORER_TELEMETRYSTORE_THREADS
	SIGNOZ_OTEL_COLLECTOR_BATCH_SEND_MAX_SIZE
	SIGNOZ_OTEL_COLLECTOR_BATCH_SEND_SIZE
	SIGNOZ_OTEL_COLLECTOR_METER_BATCH_SEND_MAX_SIZE
	SIGNOZ_OTEL_COLLECTOR_METER_BATCH_SEND_SIZE
	SIGNOZ_PROMETHEUS_ACTIVE__QUERY__TRACKER_MAX__CONCURRENT
	SIGNOZ_QUERIER_MAX__CONCURRENT__QUERIES
	SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_SETTINGS_MAX__BYTES__TO__READ
	SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_SETTINGS_MAX__EXECUTION__TIME
	SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_SETTINGS_MAX__EXECUTION__TIME__LEAF
	SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_SETTINGS_MAX__RESULT__ROWS
	SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_SETTINGS_TIMEOUT__BEFORE__CHECKING__EXECUTION__SPEED
	SIGNOZ_TELEMETRYSTORE_MAX__IDLE__CONNS
	SIGNOZ_TELEMETRYSTORE_MAX__OPEN__CONNS
	SIGNOZ_TOKENIZER_OPAQUE_TOKEN_MAX__PER__USER
	ZOO_ADMIN_SERVER_PORT_NUMBER
	ZOO_AUTOPURGE_INTERVAL
	ZOO_PROMETHEUS_METRICS_PORT_NUMBER
	ZOO_SERVER_ID
)

aio_log() {
	echo "[signoz-aio] $*"
}

aio_error() {
	echo "[signoz-aio] $*" >&2
}

is_true() {
	case "${1-}" in
	1 | true | TRUE | yes | YES | on | ON) return 0 ;;
	*) return 1 ;;
	esac
}

is_false() {
	case "${1-}" in
	0 | false | FALSE | no | NO | off | OFF) return 0 ;;
	*) return 1 ;;
	esac
}

normalize_blank_env() {
	local name
	for name in "$@"; do
		if [[ -n ${!name+x} && -z ${!name} ]]; then
			unset "${name}"
		fi
	done
}

normalize_upstream_env() {
	local name
	for name in "$@"; do
		if [[ -n ${!name+x} && ${!name} == "upstream" ]]; then
			unset "${name}"
		fi
	done
}

load_generated_fallbacks() {
	local env_file="$1"
	local key value
	[[ -f ${env_file} ]] || return 0
	while IFS='=' read -r key value; do
		[[ -n ${key} && ${key} != \#* ]] || continue
		if [[ ! ${key} =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
			continue
		fi
		if [[ -z ${!key+x} || -z ${!key} ]]; then
			value="${value%\"}"
			value="${value#\"}"
			export "${key}=${value}"
		fi
	done <"${env_file}"
}

require_bool_if_set() {
	local name="$1"
	[[ -n ${!name+x} ]] || return 0
	is_true "${!name}" || is_false "${!name}" || {
		aio_error "${name} must be a boolean (${AIO_TRUE_VALUES} or ${AIO_FALSE_VALUES}); got '${!name}'."
		return 1
	}
}

require_integer_if_set() {
	local name="$1"
	[[ -n ${!name+x} ]] || return 0
	if [[ ! ${!name} =~ ^[0-9]+$ ]]; then
		aio_error "${name} must be a non-negative integer; got '${!name}'."
		return 1
	fi
}

require_one_of_if_set() {
	local name="$1"
	shift
	local allowed value
	[[ -n ${!name+x} ]] || return 0
	value="${!name}"
	for allowed in "$@"; do
		if [[ ${value} == "${allowed}" ]]; then
			return 0
		fi
	done
	aio_error "${name} must be one of: $*; got '${value}'."
	return 1
}

require_nonempty_if_true() {
	local flag="$1"
	local required="$2"
	[[ -n ${!flag+x} ]] || return 0
	is_true "${!flag}" || return 0
	if [[ -z ${!required+x} || -z ${!required} ]]; then
		aio_error "${required} is required when ${flag}=true."
		return 1
	fi
}

validate_runtime_config() {
	local name

	normalize_blank_env "${AIO_BLANK_AS_UNSET_VARS[@]}"
	normalize_upstream_env "${AIO_UPSTREAM_AS_UNSET_VARS[@]}"

	for name in "${AIO_BOOLEAN_VARS[@]}"; do
		require_bool_if_set "${name}" || return 1
	done

	for name in "${AIO_INTEGER_VARS[@]}"; do
		require_integer_if_set "${name}" || return 1
	done

	case "${SIGNOZ_SQLSTORE_PROVIDER:-sqlite}" in
	sqlite | postgres) ;;
	*)
		aio_error "SIGNOZ_SQLSTORE_PROVIDER must be sqlite or postgres; got '${SIGNOZ_SQLSTORE_PROVIDER}'."
		return 1
		;;
	esac
	require_one_of_if_set SIGNOZ_SQLSTORE_SQLITE_MODE wal delete || return 1
	require_one_of_if_set SIGNOZ_SQLSTORE_SQLITE_TRANSACTION__MODE deferred immediate exclusive || return 1
	require_one_of_if_set SIGNOZ_CACHE_PROVIDER memory redis || return 1
	require_one_of_if_set SIGNOZ_INSTRUMENTATION_LOGS_LEVEL info debug warn error || return 1
	require_one_of_if_set SIGNOZ_AUDITOR_PROVIDER noop otlphttp || return 1
	require_one_of_if_set SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__TLS__MIN__VERSION TLS12 TLS13 || return 1
	require_one_of_if_set SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__TLS__MAX__VERSION TLS12 TLS13 || return 1

	if [[ ${SIGNOZ_SQLSTORE_PROVIDER:-sqlite} == "postgres" && -z ${SIGNOZ_SQLSTORE_POSTGRES_DSN-} ]]; then
		aio_error "SIGNOZ_SQLSTORE_PROVIDER=postgres requires SIGNOZ_SQLSTORE_POSTGRES_DSN."
		return 1
	fi

	if [[ ${SIGNOZ_CACHE_PROVIDER:-memory} == "redis" && -z ${SIGNOZ_CACHE_REDIS_HOST-} ]]; then
		aio_error "SIGNOZ_CACHE_PROVIDER=redis requires SIGNOZ_CACHE_REDIS_HOST."
		return 1
	fi

	if is_true "${SIGNOZ_USE_EXTERNAL_CLICKHOUSE:-false}"; then
		if [[ -z ${SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN-} || ${SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN} == "${AIO_DEFAULT_CLICKHOUSE_DSN}" ]]; then
			aio_error "SIGNOZ_USE_EXTERNAL_CLICKHOUSE=true requires SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN to point at an external ClickHouse endpoint."
			return 1
		fi
		if [[ -z ${SIGNOZ_CLICKHOUSE_HEALTHCHECK_URL-} || ${SIGNOZ_CLICKHOUSE_HEALTHCHECK_URL} == "${AIO_DEFAULT_CLICKHOUSE_HEALTHCHECK_URL}" ]]; then
			aio_error "SIGNOZ_USE_EXTERNAL_CLICKHOUSE=true requires SIGNOZ_CLICKHOUSE_HEALTHCHECK_URL to point at the external ClickHouse HTTP /ping endpoint."
			return 1
		fi
	elif [[ ${SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN:-${AIO_DEFAULT_CLICKHOUSE_DSN}} != "${AIO_DEFAULT_CLICKHOUSE_DSN}" ]]; then
		aio_error "Set SIGNOZ_USE_EXTERNAL_CLICKHOUSE=true when overriding SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN."
		return 1
	fi

	require_nonempty_if_true SIGNOZ_USER_ROOT_ENABLED SIGNOZ_USER_ROOT_EMAIL || return 1
	require_nonempty_if_true SIGNOZ_USER_ROOT_ENABLED SIGNOZ_USER_ROOT_PASSWORD || return 1
	require_nonempty_if_true SIGNOZ_EMAILING_ENABLED SIGNOZ_EMAILING_SMTP_FROM || return 1

	return 0
}

wait_for_http_url() {
	local url="$1"
	local label="$2"
	local timeout="${SIGNOZ_AIO_WAIT_TIMEOUT_SECONDS:-300}"
	local deadline=$((SECONDS + timeout))
	until curl -fsS "${url}" >/dev/null 2>&1; do
		if ((SECONDS >= deadline)); then
			aio_error "Timed out after ${timeout}s waiting for ${label} at ${url}."
			return 1
		fi
		sleep 2
	done
}
